"use client"

import { FormEvent } from "react"
import { Pencil, Plus, Settings2, Trash2 } from "lucide-react"
import type { FixedSchedule, Plan, Preferences } from "@/lib/types"
import { dateKey, duration, formatDate, formatTime, weekDays } from "@/components/planner/helpers"
import { ScheduleDialog } from "@/components/planner/schedule-dialog"
import { LoadingCards } from "@/components/planner/shared"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function WeekView({ loading, plans, schedules, preferences, setPreferences, refresh, removeSchedule, savePreferences }: { loading: boolean; plans: Plan[]; schedules: FixedSchedule[]; preferences: Preferences; setPreferences: (value: Preferences) => void; refresh: () => Promise<void>; removeSchedule: (id: number) => Promise<void>; savePreferences: (event: FormEvent) => Promise<void> }) {
  const days = weekDays()
  return <section aria-labelledby="week-heading"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-semibold text-[#356859]">THIS WEEK</p><h2 id="week-heading" className="text-2xl font-bold tracking-tight md:text-3xl">한눈에 보는 주간 계획</h2></div><ScheduleDialog trigger={<Button variant="outline" className="h-11 rounded-xl bg-white"><Plus />고정 일정</Button>} onSaved={refresh} /></div>
    {loading ? <LoadingCards /> : <div className="grid gap-4 lg:grid-cols-7">{days.map((day) => { const dayPlans = plans.filter((plan) => dateKey(plan.start_datetime) === day); const fixed = schedules.filter((item) => dateKey(item.start_datetime) === day); const isToday = day === dateKey(new Date()); return <section key={day} className={`min-w-0 rounded-[1.2rem] border p-4 ${isToday ? "border-[#7DA394] bg-[#F0F7F3]" : "bg-white"}`}><div className="mb-4 flex items-center justify-between lg:block"><div><p className={`text-sm font-bold ${isToday ? "text-[#285A4D]" : "text-[#68746E]"}`}>{formatDate(`${day}T12:00:00+09:00`, { weekday: "short" })}</p><p className="mt-1 text-2xl font-bold text-[#263A33]">{Number(day.slice(-2))}</p></div>{isToday && <Badge className="bg-[#356859]">오늘</Badge>}</div><div className="grid gap-2">{dayPlans.map((plan) => <div key={`p-${plan.id}`} className="rounded-xl border-l-4 border-[#356859] bg-white p-3 shadow-sm"><p className="text-xs font-semibold text-[#66736D]">{formatTime(plan.start_datetime)} · {duration(plan.start_datetime, plan.end_datetime)}분</p><p className="mt-1 break-words text-sm font-semibold text-[#263A33]">{plan.title}</p></div>)}{fixed.map((item) => <div key={`s-${item.id}`} className="rounded-xl border-l-4 border-[#D17B52] bg-[#FFF7F1] p-3"><p className="text-xs font-semibold text-[#9A6046]">{formatTime(item.start_datetime)}–{formatTime(item.end_datetime)}</p><div className="mt-1 flex items-start justify-between gap-1"><p className="break-words text-sm font-semibold text-[#5D4034]">{item.title}</p><div className="flex shrink-0"><ScheduleDialog schedule={item} trigger={<button aria-label="고정 일정 수정" className="rounded p-1 text-[#98634C] hover:bg-white"><Pencil className="size-3.5" /></button>} onSaved={refresh} /><AlertDialog><AlertDialogTrigger asChild><button aria-label="고정 일정 삭제" className="rounded p-1 text-[#98634C] hover:bg-white"><Trash2 className="size-3.5" /></button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>‘{item.title}’ 일정을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>기존 계획이 이 일정과 충돌하게 되면 삭제가 거절됩니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => void removeSchedule(item.id)}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div></div>)}{dayPlans.length === 0 && fixed.length === 0 && <p className="rounded-xl border border-dashed py-5 text-center text-sm text-[#929A96]">비어 있음</p>}</div></section>})}</div>}
    <form onSubmit={savePreferences} className="mt-7 rounded-[1.35rem] border bg-white p-5 sm:p-6"><div className="mb-5 flex items-center gap-2"><Settings2 className="size-5 text-[#356859]" /><div><h3 className="font-bold text-[#263A33]">계획 가능 시간</h3><p className="text-sm text-[#74807A]">한국 시간 기준, 플래너가 사용할 수 있는 범위입니다.</p></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><label className="grid gap-1.5 text-sm font-medium">평일 시작<Input type="time" value={preferences.weekday_available_from.slice(0, 5)} onChange={(e) => setPreferences({ ...preferences, weekday_available_from: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">평일 종료<Input type="time" value={preferences.weekday_available_until.slice(0, 5)} onChange={(e) => setPreferences({ ...preferences, weekday_available_until: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">주말 시작<Input type="time" value={preferences.weekend_available_from.slice(0, 5)} onChange={(e) => setPreferences({ ...preferences, weekend_available_from: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">주말 종료<Input type="time" value={preferences.weekend_available_until.slice(0, 5)} onChange={(e) => setPreferences({ ...preferences, weekend_available_until: e.target.value })} /></label><label className="grid gap-1.5 text-sm font-medium">하루 최대(분)<Input type="number" min={1} max={1440} value={preferences.max_daily_planning_minutes} onChange={(e) => setPreferences({ ...preferences, max_daily_planning_minutes: Number(e.target.value) })} /></label></div><div className="mt-5 flex justify-end"><Button type="submit" className="bg-[#183D35]">시간 설정 저장</Button></div></form>
  </section>
}
